# Generated by Django 4.2.3 on 2023-12-19 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='apiitems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_id', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=200)),
                ('item_name', models.CharField(max_length=200)),
                ('unit', models.CharField(max_length=200)),
                ('status', models.CharField(max_length=200)),
                ('source', models.CharField(max_length=200)),
                ('is_linked_with_zohocrm', models.BooleanField()),
                ('zcrm_product_id', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=200)),
                ('rate', models.DecimalField(decimal_places=6, max_digits=20)),
                ('tax_id', models.CharField(max_length=200)),
                ('item_tax_preferences_tax_specification', models.CharField(max_length=200)),
                ('item_tax_preferences_tax_name_formatted', models.CharField(max_length=200)),
                ('item_tax_preferences_tax_type', models.IntegerField()),
                ('item_tax_preferences_tax_name', models.CharField(max_length=200)),
                ('item_tax_preferences_tax_percentage', models.IntegerField()),
                ('item_tax_preferences_tax_id', models.CharField(max_length=200)),
                ('item_tax_preferences_tax_specification2', models.CharField(max_length=200)),
                ('item_tax_preferences_tax_name_formatted2', models.CharField(max_length=200)),
                ('item_tax_preferences_tax_type2', models.IntegerField()),
                ('item_tax_preferences_tax_name2', models.CharField(max_length=200)),
                ('item_tax_preferences_tax_percentage2', models.IntegerField()),
                ('item_tax_preferences_tax_id2', models.CharField(max_length=200)),
                ('tax_name', models.CharField(max_length=200)),
                ('tax_percentage', models.IntegerField()),
                ('purchase_account_id', models.CharField(max_length=200)),
                ('purchase_account_name', models.CharField(max_length=200)),
                ('account_id', models.CharField(max_length=200)),
                ('account_name', models.CharField(max_length=200)),
                ('purchase_description', models.CharField(max_length=200)),
                ('purchase_rate', models.DecimalField(decimal_places=6, max_digits=20)),
                ('item_type', models.CharField(max_length=200)),
                ('product_type', models.CharField(max_length=200)),
                ('is_taxable', models.BooleanField()),
                ('tax_exemption_id', models.CharField(max_length=200)),
                ('tax_exemption_code', models.CharField(max_length=200)),
                ('has_attachment', models.BooleanField()),
                ('sku', models.CharField(max_length=200)),
                ('image_name', models.CharField(max_length=200)),
                ('image_type', models.CharField(max_length=200)),
                ('image_document_id', models.CharField(max_length=200)),
                ('created_time', models.CharField(max_length=200)),
                ('last_modified_time', models.CharField(max_length=200)),
                ('hsn_or_sac', models.CharField(max_length=200)),
                ('cf_design_hours', models.CharField(max_length=200)),
                ('cf_design_hours_unformatted', models.CharField(max_length=200)),
            ],
        ),
    ]
