# Generated by Django 4.2.3 on 2023-12-08 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Grnentry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grnentry_GRNNO', models.CharField(max_length=200)),
                ('grnentry_MATERIALDESCRIPTION', models.TextField(max_length=200)),
                ('grnentry_MATERIALGRADE', models.CharField(max_length=200)),
                ('grnentry_QUANTITYTYPE', models.CharField(max_length=200)),
                ('grnentry_NOQUANTITY', models.IntegerField()),
                ('grnentry_DATETIME', models.DateTimeField(max_length=200)),
                ('grnentry_STOREOWNER', models.TextField(max_length=200)),
                ('grnentry_ORDERTYPE', models.CharField(max_length=200)),
                ('grnentry_CUSTOMERCODE', models.CharField(max_length=200)),
                ('grnentry_PONO', models.CharField(max_length=200)),
                ('grnentry_CHALLANNO', models.CharField(max_length=200)),
                ('grnentry_COMMENTS', models.TextField(max_length=200)),
            ],
        ),
    ]
