# Generated by Django 4.2.3 on 2024-01-10 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grnentry', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='orderUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('update_GRNNO', models.CharField(max_length=200)),
                ('update_desc', models.CharField(max_length=200)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
