# Generated by Django 4.2.3 on 2024-01-11 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grnentry', '0002_orderupdate'),
    ]

    operations = [
        migrations.CreateModel(
            name='order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('GRNNO', models.CharField(max_length=200)),
                ('quantitycheck', models.BooleanField()),
                ('report', models.CharField(max_length=200)),
                ('exptime', models.DateTimeField()),
                ('acttime', models.DateTimeField()),
                ('image', models.ImageField(upload_to='')),
            ],
        ),
    ]
