# Generated by Django 4.2.3 on 2024-02-03 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grnentry', '0003_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='vendor_name',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
    ]
