# Generated by Django 4.2.3 on 2024-02-24 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grnentry', '0004_order_vendor_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderupdate',
            old_name='update_GRNNO',
            new_name='GRNNO',
        ),
    ]
