# Generated by Django 4.2.3 on 2024-04-06 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grnentry', '0005_rename_update_grnno_orderupdate_grnno'),
    ]

    operations = [
        migrations.DeleteModel(
            name='orderUpdate',
        ),
        migrations.AlterField(
            model_name='order',
            name='acttime',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='quantitycheck',
            field=models.BooleanField(default=False),
        ),
    ]
