# Generated by Django 4.2.3 on 2024-04-06 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grnentry', '0006_delete_orderupdate_alter_order_acttime_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='quantitycheck',
            field=models.BooleanField(default=False, verbose_name='quantity check'),
        ),
    ]
