# Generated by Django 4.2.3 on 2024-04-12 09:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('grnentry', '0008_order_status_alter_order_quantitycheck'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('GRNNO', models.CharField(max_length=100)),
                ('vendor_name', models.CharField(max_length=100)),
                ('exptime', models.DateTimeField()),
                ('quantitycheck', models.BooleanField(default=False)),
                ('image', models.ImageField(upload_to='images/')),
                ('report', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ProcessDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('process', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=255)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('quantity', models.IntegerField()),
                ('form_data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grnentry.formdata')),
            ],
        ),
    ]
