# Generated by Django 4.2.3 on 2024-04-12 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grnentry', '0009_formdata_processdetails'),
    ]

    operations = [
        migrations.RenameField(
            model_name='processdetails',
            old_name='form_data',
            new_name='GRNNO',
        ),
    ]
