# Generated by Django 4.2.3 on 2024-04-15 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grnentry', '0011_rename_grnno_processdetails_form_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='processdetails',
            name='completed',
            field=models.BooleanField(default=False),
        ),
    ]
