# Generated by Django 4.2.3 on 2024-04-15 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grnentry', '0012_processdetails_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='processdetails',
            name='completed_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
