# Generated by Django 4.2.3 on 2024-04-16 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grnentry', '0013_processdetails_completed_time'),
    ]

    operations = [
        migrations.DeleteModel(
            name='order',
        ),
        migrations.AddField(
            model_name='formdata',
            name='order_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Completed', 'Completed')], default='Pending', max_length=50),
        ),
    ]
