# Generated by Django 4.2.3 on 2024-04-16 18:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('grnentry', '0014_delete_order_formdata_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processdetails',
            name='form_data',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='process_details', to='grnentry.formdata'),
        ),
    ]
