# Generated by Django 4.2.3 on 2024-04-16 18:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('grnentry', '0015_alter_processdetails_form_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formdata',
            name='order_status',
        ),
        migrations.AlterField(
            model_name='processdetails',
            name='form_data',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grnentry.formdata'),
        ),
    ]
