# Generated by Django 4.2.3 on 2024-04-16 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grnentry', '0016_remove_formdata_order_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='formdata',
            name='order_status',
            field=models.CharField(default='Pending', max_length=50),
        ),
    ]
