# Generated by Django 4.2.3 on 2024-04-17 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grnentry', '0017_formdata_order_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SOORDER', models.CharField(max_length=100)),
                ('GRNNO', models.CharField(max_length=100)),
                ('FINISHEDQTY', models.IntegerField()),
                ('PDIREPORT', models.FileField(upload_to='pdireports/')),
                ('TTL_QNT_DISPATCH', models.IntegerField()),
                ('INVOICENO', models.CharField(max_length=100)),
                ('CUSTOMERNAME', models.CharField(max_length=100)),
                ('BUYERNAME', models.CharField(max_length=100)),
                ('SALESREPRESENT', models.CharField(max_length=100)),
                ('PARTCOST', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
