# Generated by Django 4.2.3 on 2024-04-17 07:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('grnentry', '0018_delivery'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='delivery',
            name='GRNNO',
        ),
        migrations.AddField(
            model_name='delivery',
            name='form_data',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='grnentry.formdata'),
            preserve_default=False,
        ),
    ]
