# Generated by Django 4.2.3 on 2024-04-20 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grnentry', '0019_remove_delivery_grnno_delivery_form_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formdata',
            name='order_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Completed', 'Completed'), ('Delivered', 'Delivered')], default='Pending', max_length=50),
        ),
    ]
