# Generated by Django 4.2.3 on 2024-04-20 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grnentry', '0020_alter_formdata_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='formdata',
            name='dispatch_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='formdata',
            name='order_status',
            field=models.CharField(default='Pending', max_length=50),
        ),
    ]
