# Generated by Django 4.2.3 on 2024-04-20 08:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('grnentry', '0021_formdata_dispatch_time_alter_formdata_order_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remaining_quantity', models.IntegerField(default=0)),
                ('form_data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grnentry.formdata')),
            ],
        ),
    ]
