# Generated by Django 4.2.3 on 2024-04-27 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grnentry', '0023_grnentry1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grnentry1',
            name='grnentry_ORDERTYPE',
            field=models.CharField(choices=[('WITH MATERIAL', 'With Material'), ('JOB WORK', 'Job Work')], max_length=200),
        ),
        migrations.AlterField(
            model_name='grnentry1',
            name='grnentry_QUANTITYTYPE',
            field=models.CharField(choices=[('KG', 'KG'), ('NO_S', "NO'S")], max_length=200),
        ),
        migrations.AlterField(
            model_name='grnentry1',
            name='grnentry_STOREOWNER',
            field=models.CharField(choices=[('YOGESH PALKAR', 'YOGESH PALKAR'), ('PRANAV PATIL', 'PRANAV PATIL'), ('SHUBHAM BHALERAO', 'SHUBHAM BHALERAO')], max_length=200),
        ),
    ]
