# Generated by Django 4.2.3 on 2024-04-27 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grnentry', '0025_delete_grnentry_remove_formdata_grnno_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='grnentry1',
            name='status',
            field=models.CharField(default='Pending', max_length=50),
        ),
    ]
