# Generated by Django 4.2.3 on 2024-04-27 18:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('grnentry', '0026_grnentry1_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='delivery',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='grnentry.delivery'),
            preserve_default=False,
        ),
    ]
