# Generated by Django 4.2.3 on 2024-06-07 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grnentry', '0027_inventory_delivery'),
    ]

    operations = [
        migrations.CreateModel(
            name='fields',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field', models.CharField(max_length=200)),
            ],
        ),
    ]
