# Generated by Django 4.2.3 on 2024-06-07 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grnentry', '0028_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_description', models.CharField(max_length=200)),
                ('DRAW_NO', models.CharField(max_length=200)),
                ('Material_Grade', models.CharField(max_length=200)),
                ('Finish_size', models.CharField(max_length=200)),
                ('Raw_material_size', models.CharField(max_length=200)),
                ('order_size', models.CharField(max_length=200)),
                ('DRAWING_PDF', models.FileField(upload_to='materialpdf/')),
            ],
        ),
    ]
