# Generated by Django 4.2.3 on 2024-06-08 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grnentry', '0030_employee_info'),
    ]

    operations = [
        migrations.CreateModel(
            name='calibration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inst_name', models.CharField(max_length=200)),
                ('make', models.CharField(choices=[('mithutoyo', 'mithutoyo'), ('insize', 'insize'), ('bakers', 'bakers'), ('ensons', 'ensons'), ('aerospace', 'aerospace'), ('workzone', 'workzone')], max_length=200)),
                ('least_count', models.IntegerField()),
                ('least_count_unit', models.CharField(choices=[('mm', 'mm'), ('cm', 'cm'), ('m', 'm'), ('km', 'km'), ('in', 'in'), ('ft', 'ft'), ('yd', 'yd'), ('mi', 'mi')], max_length=200)),
                ('least_range', models.IntegerField()),
                ('max_range', models.IntegerField()),
                ('range_unit', models.CharField(choices=[('mm', 'mm'), ('cm', 'cm'), ('m', 'm'), ('km', 'km'), ('in', 'in'), ('ft', 'ft'), ('yd', 'yd'), ('mi', 'mi')], max_length=200)),
                ('location', models.CharField(max_length=200)),
                ('calibrated_date', models.DateTimeField()),
                ('next_calibration_due_date', models.DateTimeField()),
                ('remark', models.CharField(max_length=200)),
            ],
        ),
    ]
