# Generated by Django 4.2.3 on 2024-06-08 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grnentry', '0032_master_component'),
    ]

    operations = [
        migrations.AddField(
            model_name='grnentry1',
            name='REVISIONNO',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
