# Generated by Django 4.2.3 on 2024-06-10 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grnentry', '0033_grnentry1_revisionno'),
    ]

    operations = [
        migrations.AddField(
            model_name='grnentry1',
            name='FILE',
            field=models.FileField(default=12, upload_to='grnentryfile/'),
            preserve_default=False,
        ),
    ]
