# Generated by Django 4.2.3 on 2024-06-12 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grnentry', '0034_grnentry1_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='outsourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grnno', models.CharField(max_length=200)),
                ('supplier_name', models.CharField(max_length=200)),
                ('operation_name', models.CharField(max_length=200)),
                ('part_desc', models.CharField(max_length=200)),
                ('quantity', models.IntegerField()),
                ('out_date', models.DateTimeField()),
                ('accepted_qty', models.IntegerField()),
                ('rate', models.IntegerField()),
                ('status', models.CharField(max_length=200)),
            ],
        ),
    ]
