# Generated by Django 4.2.3 on 2024-06-17 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grnentry', '0038_processdetail'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProcessDetail',
        ),
    ]
