# Generated by Django 5.0.6 on 2024-06-21 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grnentry', '0039_delete_processdetail'),
    ]

    operations = [
        migrations.AddField(
            model_name='grnentry1',
            name='customername',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='grnentry1',
            name='grnentry_MATERIALGRADE',
            field=models.CharField(max_length=200),
        ),
    ]
