# Generated by Django 5.0.6 on 2024-06-21 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grnentry', '0041_remove_formdata_exptime_remove_formdata_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grnentry1',
            name='grnentry_DATETIME',
            field=models.DateField(auto_now_add=True, max_length=200),
        ),
    ]
