# Generated by Django 5.0.6 on 2024-06-21 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grnentry', '0042_alter_grnentry1_grnentry_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grnentry1',
            name='grnentry_EXPTIME',
            field=models.DateField(blank=True, max_length=200, null=True),
        ),
    ]
