# Generated by Django 4.2.3 on 2024-06-23 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grnentry', '0043_alter_grnentry1_grnentry_exptime'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='delivery',
            name='CUSTOMERNAME',
        ),
        migrations.RemoveField(
            model_name='delivery',
            name='SOORDER',
        ),
    ]
