# Generated by Django 4.2.3 on 2024-06-23 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grnentry', '0047_remove_outsourse_receive_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='outsourse',
            name='rejected_qty',
        ),
        migrations.RemoveField(
            model_name='outsourse',
            name='supplier_process_name',
        ),
        migrations.AddField(
            model_name='delivery',
            name='CUSTOMERNAME',
            field=models.CharField(default=12, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='outsourse',
            name='out_date',
            field=models.DateTimeField(),
        ),
    ]
