# Generated by Django 4.2.3 on 2024-06-23 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grnentry', '0048_remove_outsourse_rejected_qty_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outsourse',
            name='out_date',
            field=models.DateField(),
        ),
    ]
