# Generated by Django 4.2.3 on 2024-06-23 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grnentry', '0049_alter_outsourse_out_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Outsourse1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grnno', models.CharField(max_length=200)),
                ('supplier_name', models.CharField(max_length=200)),
                ('operation_name', models.CharField(max_length=200)),
                ('part_desc', models.CharField(max_length=200)),
                ('quantity', models.IntegerField()),
                ('out_date', models.DateField()),
                ('accepted_qty', models.IntegerField()),
                ('rate', models.IntegerField()),
                ('status', models.CharField(default='pending', max_length=200)),
                ('completed_time', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='outsourse',
        ),
    ]
