# Generated by Django 4.2.3 on 2024-06-23 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grnentry', '0050_outsourse1_delete_outsourse'),
    ]

    operations = [
        migrations.AddField(
            model_name='outsourse1',
            name='rejected_qty',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='outsourse1',
            name='supplier_process_name',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
