# Generated by Django 4.2.3 on 2024-06-23 13:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('grnentry', '0051_outsourse1_rejected_qty_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='outsourse1',
            name='receive_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
