# Generated by Django 4.2.3 on 2024-06-23 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grnentry', '0053_outsourse1_dc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='outsourse1',
            name='dc',
        ),
    ]
