# Generated by Django 4.2.3 on 2024-06-23 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grnentry', '0054_remove_outsourse1_dc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='delivery',
            name='CUSTOMERNAME',
        ),
        migrations.AddField(
            model_name='delivery',
            name='DELIVERYCHALLAN',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='delivery',
            name='OPTIONDC',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
