# Generated by Django 4.2.3 on 2024-06-24 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grnentry', '0055_remove_delivery_customername_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery',
            name='OPTIONDC',
            field=models.CharField(choices=[('OPTIONDC', 'OPTIONDC'), ('DELIVERYCHALLAN', 'DELIVERYCHALLAN')], max_length=200),
        ),
    ]
