# Generated by Django 4.2.3 on 2024-06-24 10:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('grnentry', '0057_alter_delivery_optiondc'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='DATE',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
