# Generated by Django 4.2.3 on 2024-06-24 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grnentry', '0058_delivery_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='processdetails',
            name='acc_qty',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='processdetails',
            name='rej_qty',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
