# Generated by Django 4.2.3 on 2024-06-24 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grnentry', '0059_processdetails_acc_qty_processdetails_rej_qty'),
    ]

    operations = [
        migrations.AddField(
            model_name='formdata',
            name='ttl_rejected_qty',
            field=models.IntegerField(default=0),
        ),
    ]
