# Generated by Django 4.2.3 on 2024-06-24 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grnentry', '0060_formdata_ttl_rejected_qty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processdetails',
            name='acc_qty',
            field=models.IntegerField(default='0'),
        ),
        migrations.AlterField(
            model_name='processdetails',
            name='rej_qty',
            field=models.IntegerField(default='0'),
        ),
    ]
