# Generated by Django 4.2.3 on 2024-06-26 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grnentry', '0063_alter_outsourse1_accepted_qty_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='formdata',
            name='ttl_dispatch_qty',
            field=models.IntegerField(default=0),
        ),
    ]
