# Generated by Django 4.2.3 on 2024-06-26 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grnentry', '0064_formdata_ttl_dispatch_qty'),
    ]

    operations = [
        migrations.AddField(
            model_name='formdata',
            name='rem_qty_dispatch',
            field=models.IntegerField(default=0),
        ),
    ]
