# Generated by Django 4.2.3 on 2024-06-27 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grnentry', '0065_formdata_rem_qty_dispatch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outsourse1',
            name='receive_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
