from django.contrib import admin
from apiitems.models import apiitems
# Register your models here.
class apiitems1(admin.ModelAdmin):
    list_display=('item_id',
                  'name',
                  'item_name',
                  'unit',
                  'status',
                  'source',
                  'is_linked_with_zohocrm',
                  'zcrm_product_id',
                  'description',
                  'rate',
                  'tax_id',
                  'item_tax_preferences_tax_specification',
                  'item_tax_preferences_tax_name_formatted',
                  'item_tax_preferences_tax_type',
                  'item_tax_preferences_tax_name',
                  'item_tax_preferences_tax_percentage',
                  'item_tax_preferences_tax_id',
                  'item_tax_preferences_tax_specification2',
                  'item_tax_preferences_tax_name_formatted2',
                  'item_tax_preferences_tax_type2',
                  'item_tax_preferences_tax_name2',
                  'item_tax_preferences_tax_percentage2',
                  'item_tax_preferences_tax_id2',
                  'tax_name',
                  'tax_percentage',
                  'purchase_account_id',
                  'purchase_account_name',
                  'account_id',
                  'account_name',
                  'purchase_description',
                  'purchase_rate',
                  'item_type',
                  'product_type',
                  'is_taxable',
                  'tax_exemption_id',
                  'tax_exemption_code',
                  'has_attachment',
                  'sku',
                  'image_name',
                  'image_type',
                  'image_document_id',
                  'created_time',
                  'last_modified_time',
                  'hsn_or_sac',
                  'cf_design_hours',
                  'cf_design_hours_unformatted' )
    admin.site.register(apiitems)
