# Generated by Django 4.2.3 on 2024-01-10 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trials', '0002_salesorder1_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesorder1',
            name='div',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
    ]
