# Generated by Django 4.2.3 on 2024-02-24 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trials', '0003_salesorder1_div'),
    ]

    operations = [
        migrations.DeleteModel(
            name='salesorder1',
        ),
    ]
